### PR TITLE
Fix error pages

### LINKED ISSUE #46: Invalid path raises 500 error
Access an invalid path seems to hit 500 error instead of 404 not found (similar to #38 but that's for file not found, this is for package).

This happens for both package & version:

https://preview.hex.pm/preview/asdas/1.2.1/show/mix.exs
https://preview.hex.pm/preview/guardian/no-exists/show/mix.exs

#. Expected
Should raise 404

### PR DESCRIPTION
**Pull request by ericmj**
Closes #46.

### CODE REVIEW

File: lib/preview_web/live/preview_live.ex [hunk 1]
```diff
@@ -28,7 +36,7 @@ defmodule PreviewWeb.PreviewLive do
          canonical: canonical_url(params["package"], filename)
        )}
     else
-      {:ok, assign(socket, error: "TODO")}
+      raise Exception, plug_status: 404
```
Comment (ericmj) [inline lib/preview_web/live/preview_live.ex:39]: This does not seem like a great solution, maybe someone with better LiveView knowledge know a better way?

File: config/dev.exs [hunk 2]
```diff
@@ -11,7 +8,7 @@ config :preview,
 # with webpack to recompile .js and .css sources.
 config :preview, PreviewWeb.Endpoint,
   http: [port: 4005],
-  debug_errors: true,
+  # debug_errors: true,
```
Comment (wojtekmach) [inline config/dev.exs:11]:
```suggestion
  debug_errors: true,
```

**Review by wojtekmach — APPROVED** [review]

File: lib/preview_web/live/preview_live.ex (hunk 1 above)
Comment (wojtekmach) [reply lib/preview_web/live/preview_live.ex:39]: Maybe [`redirect/2`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#redirect/2) to a 404 page? But then again we won't have the 404 status. I think this is probably ok as is.

Comment (josevalim) [reply lib/preview_web/live/preview_live.ex:39]: This is correct. If mount fails during a LiveRedirect, we will refresh the page and go through the regular life-cycle where this will be handled by Plug.

**Review by supersimple — APPROVED** [review]
